return {
	armmship = {
		activatewhenbuilt = true,
		buildpic = "ARMMSHIP.DDS",
		buildtime = 15000,
		canmove = true,
		collisionvolumeoffsets = "0 -5 0",
		collisionvolumescales = "44 44 80",
		collisionvolumetype = "CylZ",
		corpse = "DEAD",
		energycost = 10000,
		explodeas = "largeExplosionGeneric",
		floater = true,
		footprintx = 5,
		footprintz = 5,
		health = 3350,
		idleautoheal = 5,
		idletime = 1800,
		maxacc = 0.0287,
		maxdec = 0.0387,
		metalcost = 2000,
		minwaterdepth = 12,
		movementclass = "BOAT5",
		movestate = 0,
		nochasecategory = "VTOL",
		objectname = "Units/ARMMSHIP.s3o",
		radardistance = 1000,
		script = "Units/ARMMSHIP.cob",
		seismicsignature = 0,
		selfdestructas = "largeExplosionGenericSelfd",
		sightdistance = 318.5,
		speed = 63,
		turninplace = true,
		turninplaceanglelimit = 90,
		turnrate = 350,
		waterline = 0,
		customparams = {
			maxrange = "1650",
			model_author = "FireStorm",
			normaltex = "unittextures/Arm_normal.dds",
			subfolder = "ArmShips/T2",
			techlevel = 2,
			unitgroup = "weapon",
		},
		featuredefs = {
			dead = {
				blocking = false,
				category = "corpses",
				collisionvolumeoffsets = "-1.52864837646 2.44506835934e-05 -1.26249694824",
				collisionvolumescales = "46.7322845459 37.6582489014 110.324981689",
				collisionvolumetype = "Box",
				damage = 2640,
				featuredead = "HEAP",
				footprintx = 5,
				footprintz = 5,
				height = 4,
				metal = 1000,
				object = "Units/armmship_dead.s3o",
				reclaimable = true,
			},
			heap = {
				blocking = false,
				category = "heaps",
				collisionvolumescales = "85.0 14.0 6.0",
				collisionvolumetype = "cylY",
				damage = 4032,
				footprintx = 2,
				footprintz = 2,
				height = 4,
				metal = 500,
				object = "Units/arm4X4B.s3o",
				reclaimable = true,
				resurrectable = 0,
			},
		},
		sfxtypes = {
			explosiongenerators = {
				[1] = "custom:waterwake-medium",
				[2] = "custom:bowsplash-medium",
			},
			pieceexplosiongenerators = {
				[1] = "deathceg2",
				[2] = "deathceg3",
				[3] = "deathceg4",
			},
		},
		sounds = {
			canceldestruct = "cancel2",
			underattack = "warning1",
			cant = {
				[1] = "cantdo4",
			},
			count = {
				[1] = "count6",
				[2] = "count5",
				[3] = "count4",
				[4] = "count3",
				[5] = "count2",
				[6] = "count1",
			},
			ok = {
				[1] = "sharmmov",
			},
			select = {
				[1] = "sharmsel",
			},
		},
		weapondefs = {
			missile = {
				areaofeffect = 256,
				avoidfeature = false,
				burnblow = true,
				canattackground = false,
				castshadow = false,
				cegtag = "missiletrailaa",
				craterareaofeffect = 256,
				craterboost = 0,
				cratermult = 0,
				edgeeffectiveness = 0.65,
				explosiongenerator = "custom:newnuketac",
				firestarter = 70,
				flighttime = 1.75,
				impulsefactor = 2,
				metalpershot = 0,
				model = "catapultmissile.s3o",
				name = "Tactical nuclear a2g homing missile",
				noselfdamage = true,
				range = 710,
				reloadtime = 2,
				smokecolor = 0.95,
				smokeperiod = 7,
				smokesize = 5.4,
				smoketime = 13,
				smoketrail = true,
				smoketrailcastshadow = false,
				soundhit = "tonukeex",
				soundhitwet = "splslrg",
				soundstart = "rockhvy2",
				startvelocity = 430,
				texture1 = "null",
				texture2 = "smoketrailaa3",
				tolerance = 8000,
				tracks = true,
				turnrate = 30000,
				turret = true,
				weaponacceleration = 90,
				weapontimer = 5,
				weapontype = "MissileLauncher",
				weaponvelocity = 450,
				damage = {
					commanders = 3350,
					default = 5625,
					subs = 1000,
					vtol = 562,
				},
			},
			rocket = {
				areaofeffect = 380,
				avoidfeature = false,
				avoidfriendly = false,
				cegtag = "cruisemissiletrail-tacnuke",
				collideenemy = false,
				collidefeature = false,
				collidefriendly = false,
				commandfire = true,
				craterareaofeffect = 512,
				craterboost = 1.6,
				cratermult = 0.7,
				edgeeffectiveness = 0.55,
				energypershot = 17437,
				explosiongenerator = "custom:newnuketac",
				firestarter = 0,
				flighttime = 400,
				impulsefactor = 1.1,
				metalpershot = 550,
				model = "cortronmissile.s3o",
				name = "Long range tactical g2g nuclear warheads",
				noselfdamage = true,
				range = 2250,
				reloadtime = 2,
				smokecolor = 0.7,
				smokeperiod = 9,
				smokesize = 14,
				smoketime = 60,
				smoketrail = true,
				smoketrailcastshadow = false,
				soundhit = "xplomed4",
				soundstart = "mismed1",
				texture1 = "null",
				texture2 = "smoketrailbar",
				texture3 = "null",
				tolerance = 4000,
				turnrate = 10000,
				weaponacceleration = 150,
				weapontimer = 3,
				weapontype = "StarburstLauncher",
				weaponvelocity = 1200,
				customparams = {
					stockpilelimit = 10,
				},
				damage = {
					commanders = 750,
					default = 4000,
				},
				},
			},
		},
		weapons = {
			[1] = {
				badtargetcategory = "MOBILE",
				def = "ROCKET",
				maindir = "0 .5 1",
				maxangledif = 60,
				onlytargetcategory = "SURFACE",
			},
			[2] = {
				def = "MISSILE",
				onlytargetcategory = "VTOL",
			},
		},
	},
}
